#!/bin/bash

file="/home/jack/Desktop/image_project/static/vokoscreen_captures/$(date +'%Y-%m-%d_%H-%M-%S')video2.mp4"
echo $file
ffmpeg -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 1366x760 -i :0.0 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y $file
vlc $file

echo $file

