#!/bin/bash
file="/home/jack/Desktop/image_project/static/vokoscreen_captures/$(date +'%Y-%m-%d_%H-%M-%S')video2.mp4"
echo $file

ffmpeg -f x11grab -video_size 1360x768 -framerate 24 -i :0.0 \
-f pulse -i default -preset veryfast -crf 18 -pix_fmt yuv420p $file

vlc $file

echo $file

